
import { PDFDocument, rgb, StandardFonts } from 'pdf-lib';
import { GuestData, PdfCustomization } from '../types';

/**
 * Gets the next invoice number from local storage.
 */
function getNextInvoiceId(): string {
  const current = localStorage.getItem('eturista_invoice_counter') || '0';
  const next = parseInt(current, 10) + 1;
  localStorage.setItem('eturista_invoice_counter', next.toString());
  const year = new Date().getFullYear();
  return `${next}/${year}`;
}

/**
 * Generates the Serbian Registration Invoice PDF from scratch.
 * Matches the table layout provided in the user image.
 */
export async function generateRegistrationPdf(
  guestData: GuestData,
  customization: PdfCustomization
): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595.28, 841.89]); // A4 Size
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);

  const { width, height } = page.getSize();
  const margin = 50;
  const tableTop = height - margin;
  const col1Width = 250;
  const col2Width = 250;
  const rowHeight = 30;
  const tableWidth = col1Width + col2Width;

  const invoiceId = getNextInvoiceId();
  const today = new Date().toLocaleDateString('sr-RS');
  const guestFullName = `${guestData.firstName} ${guestData.lastName}`;

  // Table Data based on the user's provided image
  const rows = [
    { label: 'Poseban racun br.', value: invoiceId },
    { label: 'Ime i prezime fizickog lica', value: customization.physicalPersonName },
    { label: 'Adresa fizickog lica', value: customization.physicalPersonAddress },
    { label: 'Vrsta i kategorija ugostiteljskog objekta', value: customization.objectType },
    { label: 'Adresa ugostiteljskog objekta', value: customization.objectAddress },
    { label: 'Ime i prezime korisnika usluga', value: guestFullName },
    { label: 'Podatak o prodajnoj ceni sa specifikacijom', value: customization.priceDetails },
    { label: 'Datum izdavanja racuna', value: today },
    { label: 'Potpis fizickog lica, izdavaoca racuna', value: '', isSignature: true },
  ];

  // Draw Table
  for (let i = 0; i < rows.length; i++) {
    const row = rows[i];
    const y = tableTop - (i + 1) * rowHeight;

    // Draw row borders
    page.drawRectangle({
      x: margin,
      y,
      width: tableWidth,
      height: rowHeight,
      borderWidth: 1,
      borderColor: rgb(0, 0, 0),
    });

    // Draw middle divider
    page.drawLine({
      start: { x: margin + col1Width, y },
      end: { x: margin + col1Width, y: y + rowHeight },
      thickness: 1,
      color: rgb(0, 0, 0),
    });

    // Draw Labels (Column 1)
    page.drawText(row.label, {
      x: margin + 10,
      y: y + 10,
      size: 10,
      font: fontRegular,
      color: rgb(0, 0, 0),
    });

    // Draw Values (Column 2)
    if (!row.isSignature) {
      page.drawText(row.value, {
        x: margin + col1Width + 10,
        y: y + 10,
        size: 10,
        font: fontBold,
        color: rgb(0, 0, 0),
      });
    } else if (customization.signatureImage) {
      try {
        const signatureImage = await pdfDoc.embedPng(customization.signatureImage);
        const dims = signatureImage.scale(0.3); // Adjust scale as needed
        page.drawImage(signatureImage, {
          x: margin + col1Width + (col2Width / 2) - (dims.width / 2),
          y: y + 2,
          width: dims.width,
          height: dims.height > rowHeight - 4 ? rowHeight - 4 : dims.height,
        });
      } catch (e) {
        console.error("Failed to embed signature", e);
      }
    } else {
      // Add a placeholder for signature area
      page.drawText('(potpis)', {
        x: margin + col1Width + col2Width / 2 - 20,
        y: y + 5,
        size: 8,
        font: fontRegular,
        color: rgb(0.5, 0.5, 0.5),
      });
    }
  }

  // Footer / App Brand
  page.drawText('Generated by eTurista Digital Assistant', {
    x: margin,
    y: margin / 2,
    size: 8,
    font: fontRegular,
    color: rgb(0.6, 0.6, 0.6),
  });

  return await pdfDoc.save();
}
